# Generated by Django 5.2.8 on 2025-12-02 01:33

import django.db.models.deletion
import django_extensions.db.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailnavigation', '0002_add_slug_and_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, help_text="Content to display on this menu item's page"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('about', 'About'), ('contact', 'Contact'), ('services', 'Services'), ('products', 'Products'), ('blog', 'Blog'), ('faq', 'FAQ'), ('team', 'Team'), ('careers', 'Careers'), ('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('custom', 'Custom')], default='custom', help_text="Select a predefined page type or choose 'Custom'", max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='URL-friendly version of title', populate_from='title'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Link to existing Wagtail page (LEAVE BLANK to use auto-generated page)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='External URL (LEAVE BLANK to use auto-generated page URL)', max_length=500, null=True),
        ),
    ]
