# Generated by Django 5.2.8 on 2025-12-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailnavigation', '0003_menuitem_content_menuitem_item_type_menuitem_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, help_text='Open link in a new tab'),
        ),
    ]
