# Generated by Django 5.2.8 on 2025-12-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailnavigation', '0004_menuitem_open_in_new_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='home_page',
            field=models.ForeignKey(blank=True, help_text="Page to display on the menu's home screen", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='menu',
            name='home_url',
            field=models.CharField(blank=True, help_text="External URL to display on the menu's home screen (overrides Page)", max_length=500, null=True),
        ),
    ]
