# Generated by Django 5.2.8 on 2025-12-04 01:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailnavigation', '0005_menu_home_page_menu_home_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='custom_footer',
            field=wagtail.fields.RichTextField(blank=True, help_text='Custom footer content. Leave blank to use the default footer.', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='custom_header',
            field=wagtail.fields.RichTextField(blank=True, help_text='Custom header content. Leave blank to use the default header.', null=True),
        ),
    ]
