# Generated by Django 5.2.8 on 2025-12-04 01:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailnavigation', '0006_menuitem_custom_footer_menuitem_custom_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='custom_footer',
            field=wagtail.fields.RichTextField(blank=True, help_text='Custom footer menu items. Leave blank to use the default menu. This replaces the menu links but keeps the copyright.', null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='custom_header',
            field=wagtail.fields.RichTextField(blank=True, help_text='Custom header menu items. Leave blank to use the default menu. This replaces the menu links but keeps the login button.', null=True),
        ),
    ]
