# Generated by Django 5.2.8 on 2025-12-04 01:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailnavigation', '0007_alter_menuitem_custom_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='custom_footer',
            field=wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the link'}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal Page', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Open in new tab', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('page', 2), ('open_in_new_tab', 3)]], {})}, help_text='Add links to display in the footer for this menu item.', null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='custom_header',
            field=wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the link'}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal Page', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Open in new tab', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('page', 2), ('open_in_new_tab', 3)]], {})}, help_text='Add links to display in the header for this menu item.', null=True),
        ),
    ]
