# Generated by Django 5.2.8 on 2025-12-04 02:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailnavigation', '0010_alter_menuitem_custom_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='custom_footer',
            field=wagtail.fields.StreamField([('link', 5)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('faq', 'FAQ'), ('contact', 'Contact'), ('custom', 'Custom')], 'help_text': 'Select the type of link'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Title (Only used for 'Custom' links)", 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal Page', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Open in new tab', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('link_type', 0), ('title', 1), ('url', 2), ('page', 3), ('open_in_new_tab', 4)]], {})}, help_text='Add links to display in the footer for this menu item.', null=True, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='custom_header',
            field=wagtail.fields.StreamField([('link', 5)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('about', 'About'), ('contact', 'Contact'), ('services', 'Services'), ('products', 'Products'), ('blog', 'Blog'), ('custom', 'Custom')], 'help_text': 'Select the type of link'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Title (Only used for 'Custom' links)", 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal Page', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Open in new tab', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('link_type', 0), ('title', 1), ('url', 2), ('page', 3), ('open_in_new_tab', 4)]], {})}, help_text='Add links to display in the header for this menu item.', null=True, verbose_name=' '),
        ),
    ]
