# Generated by Django 5.2.8 on 2025-12-07 16:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailnavigation', '0012_remove_menuitem_custom_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Content to display for this menu'),
        ),
    ]
