# Generated by Django 5.2.8 on 2025-12-10 12:34

import json
import wagtail.fields
from django.db import migrations



def convert_to_streamfield(apps, schema_editor):
    Menu = apps.get_model('wagtailnavigation', 'Menu')
    MenuItem = apps.get_model('wagtailnavigation', 'MenuItem')

    for menu in Menu.objects.all():
        if not menu.content:
            menu.content = '[]'
        else:
            cleaned = menu.content.strip()
            if not (cleaned.startswith('[') and cleaned.endswith(']')):
                new_content = [{'type': 'paragraph', 'value': menu.content}]
                menu.content = json.dumps(new_content)
        menu.save()

    for item in MenuItem.objects.all():
        if not item.content:
            item.content = '[]'
        else:
            cleaned = item.content.strip()
            if not (cleaned.startswith('[') and cleaned.endswith(']')):
                new_content = [{'type': 'paragraph', 'value': item.content}]
                item.content = json.dumps(new_content)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailnavigation', '0013_menu_content'),
    ]

    operations = [
        migrations.RunPython(convert_to_streamfield),
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('card', 12), ('button', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading Text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Heading Size'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'required': True}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'label': 'Link URL', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Link Text', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 7), ('text', 8), ('image', 9), ('link_url', 10), ('link_text', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'Button URL', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Button Text', 'required': True}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], 'label': 'Button Style'}), 16: ('wagtail.blocks.StructBlock', [[('link_url', 13), ('text', 14), ('style', 15)]], {})}, help_text='Content to display for this menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('card', 12), ('button', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading Text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Heading Size'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'required': True}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'label': 'Link URL', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Link Text', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 7), ('text', 8), ('image', 9), ('link_url', 10), ('link_text', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'Button URL', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Button Text', 'required': True}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], 'label': 'Button Style'}), 16: ('wagtail.blocks.StructBlock', [[('link_url', 13), ('text', 14), ('style', 15)]], {})}, help_text="Content to display on this menu item's page"),
        ),
    ]
